In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel(r"C:\Users\User\Desktop\Dataset.xlsx")
df_copy = df.copy()
df

,ID,Churn,Tenure,LoginDevice,TierOfCity,HomeToWarehouse,ModeOfPayment,Gender,AppSpendTime,DeviceNumber,PreferedOrder,ScoreSatisfaction,StatusOfMarital,AddressCount,Complain,OrderAmountHikeFromlastYear,Coupon,OrderNumber,DaySinceLastOrder,Cashback
0,50001,1,4.0,Mobile Phone,3,6.0,Debit Card,Female,3.0,3,Laptop & Accessory,2,Single,9,1,11.0,1.0,1.0,5.0,159.93
1,50002,1,NaN,Phone,1,8.0,UPI,Male,3.0,4,Mobile,3,Single,7,1,15.0,0.0,1.0,0.0,120.90
2,50003,1,NaN,Phone,1,30.0,Debit Card,Male,2.0,4,Mobile,3,Single,6,1,14.0,0.0,1.0,3.0,120.28
3,50004,1,0.0,Phone,3,15.0,Debit Card,Male,2.0,4,Laptop & Accessory,5,Single,8,0,23.0,0.0,1.0,3.0,134.07
4,50005,1,0.0,Phone,1,12.0,CC,Male,NaN,3,Mobile,5,Single,3,0,11.0,1.0,1.0,3.0,129.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5625,55626,0,10.0,Computer,1,30.0,Credit Card,Male,3.0,2,Laptop & Accessory,1,Married,6,0,18.0,1.0,2.0,4.0,150.71
5626,55627,0,13.0,Mobile Phone,1,13.0,Credit Card,Male,3.0,5,Fashion,5,Married,6,0,16.0,1.0,2.0,NaN,224.91
5627,55628,0,1.0,Mobile Phone,1,11.0,Debit Card,Male,3.0,2,Laptop & Accessory,4,Married,3,1,21.0,1.0,2.0,4.0,186.42
5628,55629,0,23.0,Computer,3,9.0,Credit Card,Male,4.0,5,Laptop & Accessory,4,Married,4,0,15.0,2.0,2.0,9.0,178.90
5629,55630,0,8.0,Mobile Phone,1,15.0,Credit Card,Male,3.0,2,Laptop & Accessory,3,Married,4,0,13.0,2.0,2.0,3.0,169.04

In [3]:
df.dtypes

ID                               int64
Churn                            int64
Tenure                         float64
LoginDevice                     object
TierOfCity                       int64
HomeToWarehouse                float64
ModeOfPayment                   object
Gender                          object
AppSpendTime                   float64
DeviceNumber                     int64
PreferedOrder                   object
ScoreSatisfaction                int64
StatusOfMarital                 object
AddressCount                     int64
Complain                         int64
OrderAmountHikeFromlastYear    float64
Coupon                         float64
OrderNumber                    float64
DaySinceLastOrder              float64
Cashback                       float64
dtype: object

In [4]:
null_sum = {}
for i in df:
    null_sum[i] = df[i].isnull().sum()
null_sum

{'ID': 0,
 'Churn': 0,
 'Tenure': 264,
 'LoginDevice': 0,
 'TierOfCity': 0,
 'HomeToWarehouse': 251,
 'ModeOfPayment': 0,
 'Gender': 0,
 'AppSpendTime': 255,
 'DeviceNumber': 0,
 'PreferedOrder': 0,
 'ScoreSatisfaction': 0,
 'StatusOfMarital': 0,
 'AddressCount': 0,
 'Complain': 0,
 'OrderAmountHikeFromlastYear': 265,
 'Coupon': 256,
 'OrderNumber': 258,
 'DaySinceLastOrder': 307,
 'Cashback': 0}

In [5]:
value_counts_cats = {}
for i in ['LoginDevice','ModeOfPayment','Gender','PreferedOrder','StatusOfMarital']:
    value_counts_cats[i] = len(df[i].value_counts().keys())
value_counts_cats

{'LoginDevice': 3,
 'ModeOfPayment': 7,
 'Gender': 2,
 'PreferedOrder': 6,
 'StatusOfMarital': 3}

In [6]:
df.columns
df = df.drop(['ID','Churn'],axis = 1)

In [7]:
df['Gender'] = df['Gender'].map({'Female' : 1,'Male' : 0})
df = pd.get_dummies(data = df,columns = ['LoginDevice','StatusOfMarital'])
for i in ['StatusOfMarital_Single','StatusOfMarital_Married','StatusOfMarital_Divorced','LoginDevice_Phone','LoginDevice_Mobile Phone','LoginDevice_Computer']:
    df[i] = df[i].astype(int)
for i in ['ModeOfPayment','PreferedOrder','OrderNumber','Coupon','DeviceNumber']:
    value_counts_feature = (df[i].value_counts())/len(df)
    df[i] = df[i].map(value_counts_feature)
pd.set_option("display.max_columns", None)
df

,Tenure,TierOfCity,HomeToWarehouse,ModeOfPayment,Gender,AppSpendTime,DeviceNumber,PreferedOrder,ScoreSatisfaction,AddressCount,Complain,OrderAmountHikeFromlastYear,Coupon,OrderNumber,DaySinceLastOrder,Cashback,LoginDevice_Computer,LoginDevice_Mobile Phone,LoginDevice_Phone,StatusOfMarital_Divorced,StatusOfMarital_Married,StatusOfMarital_Single
0,4.0,3,6.0,0.411012,1,3.0,0.301776,0.364121,2,9,1,11.0,0.373890,0.311012,5.0,159.93,0,1,0,0,0,1
1,NaN,1,8.0,0.073535,0,3.0,0.422202,0.143694,3,7,1,15.0,0.182948,0.311012,0.0,120.90,0,0,1,0,0,1
2,NaN,1,30.0,0.411012,0,2.0,0.422202,0.143694,3,6,1,14.0,0.182948,0.311012,3.0,120.28,0,0,1,0,0,1
3,0.0,3,15.0,0.411012,0,2.0,0.422202,0.364121,5,8,0,23.0,0.182948,0.311012,3.0,134.07,0,0,1,0,0,1
4,0.0,1,12.0,0.048490,0,NaN,0.301776,0.143694,5,3,0,11.0,0.373890,0.311012,3.0,129.60,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5625,10.0,1,30.0,0.266607,0,3.0,0.049023,0.364121,1,6,0,18.0,0.373890,0.359680,4.0,150.71,1,0,0,0,1,0
5626,13.0,1,13.0,0.266607,0,3.0,0.156483,0.146714,5,6,0,16.0,0.373890,0.359680,NaN,224.91,0,1,0,0,1,0
5627,1.0,1,11.0,0.411012,0,3.0,0.049023,0.364121,4,3,1,21.0,0.373890,0.359680,4.0,186.42,0,1,0,0,1,0
5628,23.0,3,9.0,0.266607,0,4.0,0.156483,0.364121,4,4,0,15.0,0.227886,0.359680,9.0,178.90,1,0,0,0,1,0
5629,8.0,1,15.0,0.266607,0,3.0,0.049023,0.364121,3,4,0,13.0,0.227886,0.359680,3.0,169.04,0,1,0,0,1,0

In [8]:
df_without_nulls = df.dropna()
df_without_nulls

,Tenure,TierOfCity,HomeToWarehouse,ModeOfPayment,Gender,AppSpendTime,DeviceNumber,PreferedOrder,ScoreSatisfaction,AddressCount,Complain,OrderAmountHikeFromlastYear,Coupon,OrderNumber,DaySinceLastOrder,Cashback,LoginDevice_Computer,LoginDevice_Mobile Phone,LoginDevice_Phone,StatusOfMarital_Divorced,StatusOfMarital_Married,StatusOfMarital_Single
0,4.0,3,6.0,0.411012,1,3.0,0.301776,0.364121,2,9,1,11.0,0.373890,0.311012,5.0,159.93,0,1,0,0,0,1
3,0.0,3,15.0,0.411012,0,2.0,0.422202,0.364121,5,8,0,23.0,0.182948,0.311012,3.0,134.07,0,0,1,0,0,1
5,0.0,1,22.0,0.411012,1,3.0,0.156483,0.225755,5,2,1,22.0,0.034991,0.024334,7.0,139.19,1,0,0,0,0,1
11,11.0,1,6.0,0.411012,0,3.0,0.422202,0.146714,3,10,1,13.0,0.182948,0.311012,0.0,153.81,0,1,0,0,0,1
12,0.0,1,11.0,0.064831,0,2.0,0.301776,0.143694,3,2,1,13.0,0.227886,0.359680,2.0,134.41,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5624,1.0,3,12.0,0.073535,1,2.0,0.156483,0.225755,3,2,0,19.0,0.227886,0.359680,1.0,154.66,0,1,0,0,0,1
5625,10.0,1,30.0,0.266607,0,3.0,0.049023,0.364121,1,6,0,18.0,0.373890,0.359680,4.0,150.71,1,0,0,0,1,0
5627,1.0,1,11.0,0.411012,0,3.0,0.049023,0.364121,4,3,1,21.0,0.373890,0.359680,4.0,186.42,0,1,0,0,1,0
5628,23.0,3,9.0,0.266607,0,4.0,0.156483,0.364121,4,4,0,15.0,0.227886,0.359680,9.0,178.90,1,0,0,0,1,0
5629,8.0,1,15.0,0.266607,0,3.0,0.049023,0.364121,3,4,0,13.0,0.227886,0.359680,3.0,169.04,0,1,0,0,1,0

### Tenure

In [9]:
df_tenure = df[df['Tenure'].isnull()]
df_tenure = df_tenure.drop(['Tenure'],axis=1)
df_tenure

,TierOfCity,HomeToWarehouse,ModeOfPayment,Gender,AppSpendTime,DeviceNumber,PreferedOrder,ScoreSatisfaction,AddressCount,Complain,OrderAmountHikeFromlastYear,Coupon,OrderNumber,DaySinceLastOrder,Cashback,LoginDevice_Computer,LoginDevice_Mobile Phone,LoginDevice_Phone,StatusOfMarital_Divorced,StatusOfMarital_Married,StatusOfMarital_Single
1,1,8.0,0.073535,0,3.0,0.422202,0.143694,3,7,1,15.0,0.182948,0.311012,0.0,120.90,0,0,1,0,0,1
2,1,30.0,0.411012,0,2.0,0.422202,0.143694,3,6,1,14.0,0.182948,0.311012,3.0,120.28,0,0,1,0,0,1
6,3,11.0,0.026465,0,2.0,0.301776,0.364121,2,4,0,14.0,0.182948,0.311012,0.0,120.86,0,0,1,1,0,0
7,1,6.0,0.048490,0,3.0,0.301776,0.143694,2,3,1,16.0,0.227886,0.359680,0.0,122.93,0,0,1,1,0,0
9,1,31.0,0.411012,0,2.0,0.156483,0.143694,3,2,0,12.0,0.373890,0.311012,1.0,122.93,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2756,2,8.0,0.073535,1,2.0,0.301776,0.143694,4,5,0,14.0,0.182948,0.311012,2.0,121.87,0,0,1,0,1,0
2760,1,7.0,0.048490,0,2.0,0.422202,0.143694,3,2,0,12.0,0.182948,0.311012,0.0,120.08,1,0,0,0,1,0
2773,3,7.0,0.048490,0,3.0,0.422202,0.143694,4,1,0,14.0,0.227886,0.359680,2.0,122.69,0,0,1,0,1,0
2783,3,15.0,0.109059,0,2.0,0.301776,0.225755,5,2,0,19.0,0.373890,0.311012,0.0,117.90,1,0,0,0,1,0
2802,1,8.0,0.048490,1,3.0,0.301776,0.143694,3,3,0,14.0,0.182948,0.311012,2.0,120.01,0,1,0,0,1,0

In [10]:
df_without_nulls = df_without_nulls.drop(['Tenure'],axis=1)

In [11]:
print(df_without_nulls.columns)
print(df_tenure.columns)
print(df_tenure.dtypes)
print(df_without_nulls.dtypes)

Index(['TierOfCity', 'HomeToWarehouse', 'ModeOfPayment', 'Gender',
       'AppSpendTime', 'DeviceNumber', 'PreferedOrder', 'ScoreSatisfaction',
       'AddressCount', 'Complain', 'OrderAmountHikeFromlastYear', 'Coupon',
       'OrderNumber', 'DaySinceLastOrder', 'Cashback', 'LoginDevice_Computer',
       'LoginDevice_Mobile Phone', 'LoginDevice_Phone',
       'StatusOfMarital_Divorced', 'StatusOfMarital_Married',
       'StatusOfMarital_Single'],
      dtype='object')
Index(['TierOfCity', 'HomeToWarehouse', 'ModeOfPayment', 'Gender',
       'AppSpendTime', 'DeviceNumber', 'PreferedOrder', 'ScoreSatisfaction',
       'AddressCount', 'Complain', 'OrderAmountHikeFromlastYear', 'Coupon',
       'OrderNumber', 'DaySinceLastOrder', 'Cashback', 'LoginDevice_Computer',
       'LoginDevice_Mobile Phone', 'LoginDevice_Phone',
       'StatusOfMarital_Divorced', 'StatusOfMarital_Married',
       'StatusOfMarital_Single'],
      dtype='object')
TierOfCity                       int64
HomeToWarehouse                float64
ModeOfPayment                  float64
Gender                           int64
AppSpendTime                   float64
DeviceNumber                   float64
PreferedOrder                  float64
ScoreSatisfaction                int64
AddressCount                     int64
Complain                         int64
OrderAmountHikeFromlastYear    float64
Coupon                         float64
OrderNumber                    float64
DaySinceLastOrder              float64
Cashback                       float64
LoginDevice_Computer             int32
LoginDevice_Mobile Phone         int32
LoginDevice_Phone                int32
StatusOfMarital_Divorced         int32
StatusOfMarital_Married          int32
StatusOfMarital_Single           int32
dtype: object
TierOfCity                       int64
HomeToWarehouse                float64
ModeOfPayment                  float64
Gender                           int64
AppSpendTime                   float64
DeviceNumber                   float64
PreferedOrder                  float64
ScoreSatisfaction                int64
AddressCount                     int64
Complain                         int64
OrderAmountHikeFromlastYear    float64
Coupon                         float64
OrderNumber                    float64
DaySinceLastOrder              float64
Cashback                       float64
LoginDevice_Computer             int32
LoginDevice_Mobile Phone         int32
LoginDevice_Phone                int32
StatusOfMarital_Divorced         int32
StatusOfMarital_Married          int32
StatusOfMarital_Single           int32
dtype: object

In [12]:
def euclidean(row0: dict, row1: dict) -> float:
    distance_def = 0
    for i in row1:
        if not pd.isna(row0[i]):
            distance_def += np.power(row0[i] - row1[i], 2.0)   # (two reasons, 1: make it "positive", 2: when the difference gets bigger, the distance must get "bigger" exponantionaly -- EXTREMELY
    distance_def = np.sqrt(distance_def)
    return distance_def

In [13]:
def row(row):
    distance={}
    for i in list(df_without_nulls.index):
        row1 = dict(df_without_nulls.loc[i])
        distance[i] = euclidean(row,row1)
    min_distance = min(distance.items(), key=lambda x: x[1]) 
    min_distance = list(min_distance)
    return min_distance

In [14]:
distance = {}
for i in list(df_tenure.index):
    row0 = dict(df_tenure.loc[i])
    distance[i] = row(row0)
distance

{1: [512, 8.009119411932513],
 2: [2143, 6.949298491190969],
 6: [380, 7.073143869370542],
 7: [512, 5.401843233178402],
 9: [1358, 7.728608609379726],
 15: [380, 11.725610853021113],
 22: [2710, 7.012848217290164],
 27: [380, 8.869958669162537],
 34: [512, 9.209589280819017],
 36: [1297, 9.922177180437759],
 47: [512, 6.351080346576534],
 54: [380, 5.272848108221342],
 56: [2143, 6.001439081627113],
 66: [380, 6.450417115192457],
 68: [380, 7.1195277259644865],
 82: [1358, 7.9273487757681025],
 92: [512, 5.069662360402847],
 100: [512, 7.27264755716787],
 107: [2767, 9.024682819911183],
 115: [512, 7.602882502531246],
 137: [512, 6.4121265339662505],
 147: [639, 11.47548295425404],
 160: [512, 6.006190416163453],
 171: [2747, 4.6378942283477],
 211: [380, 8.504790412085244],
 232: [512, 4.14232272426198],
 236: [380, 8.182633080725282],
 246: [2143, 7.169567169486389],
 258: [380, 6.956319498123109],
 260: [1077, 15.756929448402689],
 270: [2143, 5.946076829570331],
 274: [512, 3.872490681208317],
 291: [52, 6.484671240969102],
 294: [512, 6.760835747154337],
 316: [380, 8.19474705115136],
 332: [512, 8.008992984708422],
 351: [2143, 9.244598194725492],
 353: [2767, 9.738238321021624],
 355: [176, 10.881933959736328],
 360: [380, 5.427778868998583],
 376: [512, 9.246836267608915],
 387: [512, 4.835496338337528],
 390: [602, 4.7227642849056],
 415: [512, 9.277825729929832],
 430: [380, 6.572514333830402],
 460: [639, 7.29579133953685],
 474: [2767, 7.730020234076659],
 478: [512, 4.383031040667148],
 490: [1277, 6.4275975353946055],
 511: [2143, 7.794541101155569],
 530: [512, 5.408400065066787],
 537: [512, 4.943270662028895],
 546: [380, 8.6265032668325],
 553: [2143, 6.507298184588836],
 563: [1358, 7.6925372740728655],
 572: [1358, 7.375776914654965],
 588: [512, 4.040423535632842],
 595: [1358, 7.944527824062045],
 634: [2143, 5.822622232564392],
 637: [512, 8.027132651991737],
 638: [380, 9.015103992744628],
 644: [512, 3.821947599162959],
 652: [176, 3.8322908026831977],
 668: [1358, 8.230881502964035],
 673: [2143, 0.19094138543516875],
 690: [512, 4.256565223154317],
 703: [176, 7.78846173702451],
 715: [512, 8.215593919537865],
 734: [1358, 9.772097576108134],
 737: [1358, 6.160608008709728],
 739: [380, 9.566679732459527],
 746: [1358, 6.743257547157454],
 764: [1358, 10.457687427107347],
 766: [512, 6.7342887868034955],
 767: [639, 9.175346185099663],
 785: [52, 3.0787339103566267],
 796: [512, 2.9481218338623276],
 808: [512, 4.962204797112407],
 809: [512, 7.274795496759275],
 827: [512, 3.8798488594754974],
 847: [1277, 7.0904416557321115],
 852: [2143, 5.483470949540841],
 887: [1277, 4.828131397997604],
 891: [176, 3.22945992528196],
 892: [380, 8.567173315199819],
 898: [52, 10.582404972934262],
 903: [380, 5.961367245330428],
 910: [1297, 9.97146363546657],
 927: [602, 4.019606331614761],
 936: [176, 9.19061737901837],
 939: [512, 9.656603957913983],
 944: [2747, 6.2391553574911995],
 957: [1358, 5.598979255926611],
 958: [380, 8.667442449342934],
 962: [164, 12.393466266811336],
 967: [2143, 5.1277145147948895],
 972: [1358, 6.880208537540685],
 985: [512, 5.272234688694329],
 993: [1522, 9.949338490498361],
 1002: [380, 8.158399529978661],
 1016: [380, 6.243262355377653],
 1028: [2747, 5.511906210832214],
 1046: [380, 6.580645864958854],
 1055: [380, 7.663654480729158],
 1080: [1277, 4.691648204345783],
 1085: [2143, 12.739253048255705],
 1088: [380, 9.42242318157447],
 1097: [786, 6.344072026426432],
 1099: [1358, 6.139601784888878],
 1120: [380, 7.38849440141016],
 1121: [2767, 6.5634453840962514],
 1133: [512, 6.193938887272402],
 1141: [380, 9.419472310733337],
 1158: [1982, 3.65054223543186],
 1172: [1358, 6.581557566412395],
 1186: [176, 6.991001537031713],
 1196: [2767, 7.3454230228495625],
 1218: [380, 7.45928280734817],
 1228: [2143, 10.404831437268138],
 1242: [512, 3.7323852985350894],
 1248: [380, 8.654396062064421],
 1256: [1358, 7.663478322537369],
 1286: [512, 5.892944193169862],
 1290: [512, 4.0631914596872605],
 1303: [512, 3.788244104829711],
 1313: [2109, 8.27802393397005],
 1332: [512, 5.095564832279899],
 1347: [512, 8.009119411932513],
 1359: [2143, 6.949298491190969],
 1368: [176, 6.1755773241948875],
 1377: [380, 8.465626074784762],
 1378: [380, 7.282126351335445],
 1379: [1982, 5.216737440169776],
 1382: [1982, 4.702644118548506],
 1385: [1982, 6.02418386703248],
 1387: [1358, 7.726249570412965],
 1394: [380, 7.893926594946447],
 1413: [512, 5.250849678604004],
 1432: [2109, 11.60676291291996],
 1444: [2143, 9.024744728327883],
 1445: [380, 11.724056092659],
 1472: [1240, 7.012848217290164],
 1493: [380, 10.427084923409804],
 1494: [602, 5.53924659103839],
 1497: [380, 8.981991248751674],
 1504: [512, 9.098355681589098],
 1506: [2767, 9.922177180437759],
 1517: [512, 6.349515697579527],
 1524: [380, 5.36683586225379],
 1526: [2143, 6.0044758025287415],
 1536: [380, 6.4475904295555155],
 1538: [380, 7.192208839668115],
 1552: [1358, 7.8617046497563186],
 1562: [512, 5.069662360402847],
 1570: [1982, 7.136375908222022],
 1577: [1297, 8.913186859928386],
 1585: [512, 7.605279808131169],
 1607: [512, 6.4121265339662505],
 1617: [2109, 11.692868238633622],
 1630: [1982, 6.003154562606381],
 1641: [1277, 4.6378942283477],
 1646: [176, 0.19094138543516875],
 1681: [380, 8.619454816914187],
 1702: [512, 4.01980566096636],
 1706: [1297, 8.19648152445475],
 1716: [2143, 7.5125995507846],
 1728: [380, 7.098618243008124],
 1730: [1077, 11.587960374541325],
 1740: [2143, 6.349753621242423],
 1744: [512, 3.6071839140888633],
 1761: [1522, 6.481859493292018],
 1764: [1982, 6.611270679680264],
 1786: [380, 8.315759726177507],
 1802: [512, 8.008992984708422],
 1821: [2143, 9.244598194725492],
 1823: [2767, 9.635003144629174],
 1825: [176, 10.881933959736328],
 1830: [380, 5.424419308836259],
 1846: [512, 9.246836267608915],
 1857: [1982, 4.835496338337528],
 1860: [602, 4.7227642849056],
 1885: [512, 9.277825729929832],
 1900: [380, 6.572667957324802],
 1930: [2109, 7.29579133953685],
 1944: [2767, 7.124128916522676],
 1948: [512, 4.383031040667148],
 1960: [2747, 6.189831183240041],
 1981: [2143, 7.800271108693472],
 2000: [512, 5.408400065066787],
 2007: [512, 4.946956988972866],
 2016: [380, 8.6265032668325],
 2023: [2143, 6.504496218038817],
 2033: [1358, 7.6949066482753565],
 2042: [1358, 7.169524746784623],
 2058: [1982, 4.040423535632842],
 2065: [1358, 7.817641738228736],
 2104: [2143, 5.822622232564392],
 2107: [512, 7.899265788666691],
 2108: [380, 9.125354787623335],
 2114: [512, 3.8171749813278937],
 2122: [176, 3.837044619104934],
 2138: [1358, 8.23075882935452],
 2160: [512, 4.260845703805603],
 2173: [176, 7.786553250582394],
 2185: [512, 8.092958881073567],
 2204: [1358, 9.617374435727168],
 2207: [1358, 6.160608008709728],
 2209: [380, 9.564774042850148],
 2216: [1358, 6.596057986401262],
 2234: [1358, 10.362761132206808],
 2236: [1982, 6.582083736280303],
 2237: [2109, 9.175346185099663],
 2255: [52, 2.5524617731616877],
 2266: [512, 3.1189551070779578],
 2278: [512, 5.065563646935776],
 2279: [512, 7.343204308724429],
 2297: [512, 4.0023478070427],
 2317: [1277, 6.802526212616981],
 2322: [2143, 5.483470949540841],
 2357: [2747, 4.506756349785319],
 2361: [176, 3.22945992528196],
 2362: [380, 8.683113417010734],
 2368: [52, 10.437951733865793],
 2373: [380, 6.123841998372149],
 2380: [2767, 9.972532480305341],
 2397: [602, 4.019606331614761],
 2406: [176, 9.19061737901837],
 2409: [512, 9.7082439194738],
 2414: [2747, 5.993918549238982],
 2427: [1358, 5.598979255926611],
 2428: [380, 8.667442449342934],
 2432: [164, 12.394095280439258],
 2437: [2143, 5.1277145147948895],
 2442: [1358, 6.880208537540685],
 2455: [512, 5.272234688694329],
 2463: [1522, 9.949338490498361],
 2472: [380, 8.158275766478965],
 2486: [380, 6.246181509590289],
 2498: [1277, 5.511906210832214],
 2516: [380, 6.580645864958854],
 2525: [380, 7.663654480729158],
 2550: [2747, 4.691648204345783],
 2555: [2143, 12.73984732258795],
 2558: [380, 9.369208003490579],
 2567: [786, 6.344072026426432],
 2569: [1358, 6.142570202259198],
 2590: [380, 7.386026733433705],
 2591: [2767, 6.5634453840962514],
 2603: [512, 6.193938887272402],
 2611: [380, 9.417536832951605],
 2628: [1982, 3.7850308602007248],
 2642: [1358, 6.581557566412395],
 2656: [176, 6.991001537031713],
 2666: [1297, 7.343971837316345],
 2688: [380, 7.45928280734817],
 2698: [2143, 10.401790281007935],
 2712: [512, 3.7274980085908793],
 2718: [380, 8.654396062064421],
 2726: [1358, 7.663478322537369],
 2756: [512, 5.892944193169862],
 2760: [512, 4.184438413703264],
 2773: [512, 3.9182665563505434],
 2783: [2109, 8.27802393397005],
 2802: [512, 5.0919860906424095]}

In [15]:
for i in list(distance.keys()):
    value = int(df.loc[distance[i][0]]['Tenure'])
    df['Tenure'][i] = (value)
df['Tenure'].isnull().sum()

C:\Users\User\AppData\Local\Temp\ipykernel_25028\407031948.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Tenure'][i] = (value)

0

In [16]:
for col in df:
    if df[col].isnull().sum() != 0:
            my_dict = dict(df[col].value_counts(normalize = True))
            df[col] = df[col].fillna(pd.Series(np.random.choice(list(my_dict.keys()), p=list(my_dict.values()), size=len(df))))
df.isnull().sum()

Tenure                         0
TierOfCity                     0
HomeToWarehouse                0
ModeOfPayment                  0
Gender                         0
AppSpendTime                   0
DeviceNumber                   0
PreferedOrder                  0
ScoreSatisfaction              0
AddressCount                   0
Complain                       0
OrderAmountHikeFromlastYear    0
Coupon                         0
OrderNumber                    0
DaySinceLastOrder              0
Cashback                       0
LoginDevice_Computer           0
LoginDevice_Mobile Phone       0
LoginDevice_Phone              0
StatusOfMarital_Divorced       0
StatusOfMarital_Married        0
StatusOfMarital_Single         0
dtype: int64

In [17]:
df.isnull().sum()

Tenure                         0
TierOfCity                     0
HomeToWarehouse                0
ModeOfPayment                  0
Gender                         0
AppSpendTime                   0
DeviceNumber                   0
PreferedOrder                  0
ScoreSatisfaction              0
AddressCount                   0
Complain                       0
OrderAmountHikeFromlastYear    0
Coupon                         0
OrderNumber                    0
DaySinceLastOrder              0
Cashback                       0
LoginDevice_Computer           0
LoginDevice_Mobile Phone       0
LoginDevice_Phone              0
StatusOfMarital_Divorced       0
StatusOfMarital_Married        0
StatusOfMarital_Single         0
dtype: int64

In [18]:
df['Churn']=df_copy['Churn']
df = pd.get_dummies(data = df,columns = ['TierOfCity'])
df

,Tenure,HomeToWarehouse,ModeOfPayment,Gender,AppSpendTime,DeviceNumber,PreferedOrder,ScoreSatisfaction,AddressCount,Complain,OrderAmountHikeFromlastYear,Coupon,OrderNumber,DaySinceLastOrder,Cashback,LoginDevice_Computer,LoginDevice_Mobile Phone,LoginDevice_Phone,StatusOfMarital_Divorced,StatusOfMarital_Married,StatusOfMarital_Single,Churn,TierOfCity_1,TierOfCity_2,TierOfCity_3
0,4.0,6.0,0.411012,1,3.0,0.301776,0.364121,2,9,1,11.0,0.373890,0.311012,5.0,159.93,0,1,0,0,0,1,1,0,0,1
1,5.0,8.0,0.073535,0,3.0,0.422202,0.143694,3,7,1,15.0,0.182948,0.311012,0.0,120.90,0,0,1,0,0,1,1,1,0,0
2,0.0,30.0,0.411012,0,2.0,0.422202,0.143694,3,6,1,14.0,0.182948,0.311012,3.0,120.28,0,0,1,0,0,1,1,1,0,0
3,0.0,15.0,0.411012,0,2.0,0.422202,0.364121,5,8,0,23.0,0.182948,0.311012,3.0,134.07,0,0,1,0,0,1,1,0,0,1
4,0.0,12.0,0.048490,0,3.0,0.301776,0.143694,5,3,0,11.0,0.373890,0.311012,3.0,129.60,0,0,1,0,0,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5625,10.0,30.0,0.266607,0,3.0,0.049023,0.364121,1,6,0,18.0,0.373890,0.359680,4.0,150.71,1,0,0,0,1,0,0,1,0,0
5626,13.0,13.0,0.266607,0,3.0,0.156483,0.146714,5,6,0,16.0,0.373890,0.359680,4.0,224.91,0,1,0,0,1,0,0,1,0,0
5627,1.0,11.0,0.411012,0,3.0,0.049023,0.364121,4,3,1,21.0,0.373890,0.359680,4.0,186.42,0,1,0,0,1,0,0,1,0,0
5628,23.0,9.0,0.266607,0,4.0,0.156483,0.364121,4,4,0,15.0,0.227886,0.359680,9.0,178.90,1,0,0,0,1,0,0,0,0,1
5629,8.0,15.0,0.266607,0,3.0,0.049023,0.364121,3,4,0,13.0,0.227886,0.359680,3.0,169.04,0,1,0,0,1,0,0,1,0,0

In [19]:
df = df.drop(['TierOfCity_3','StatusOfMarital_Single','LoginDevice_Phone'],axis = 1)
df_corr = df.corr()
df_corr

,Tenure,HomeToWarehouse,ModeOfPayment,Gender,AppSpendTime,DeviceNumber,PreferedOrder,ScoreSatisfaction,AddressCount,Complain,OrderAmountHikeFromlastYear,Coupon,OrderNumber,DaySinceLastOrder,Cashback,LoginDevice_Computer,LoginDevice_Mobile Phone,StatusOfMarital_Divorced,StatusOfMarital_Married,Churn,TierOfCity_1,TierOfCity_2
Tenure,1.000000,-0.016751,0.062917,0.049854,0.011432,0.031821,-0.209289,-0.019884,0.247646,-0.018773,0.011396,-0.080806,-0.140018,0.193261,0.497274,-0.040953,0.211048,0.039177,0.082534,-0.343945,0.042795,0.016223
HomeToWarehouse,-0.016751,1.000000,-0.011299,0.002807,0.058522,-0.006871,0.037361,0.012795,-0.012293,0.025137,0.030188,0.006202,0.008502,0.011750,-0.009623,0.025989,-0.003065,-0.006431,0.027194,0.076429,-0.000502,-0.013904
ModeOfPayment,0.062917,-0.011299,1.000000,0.011866,0.054344,-0.022958,0.028593,-0.045917,0.030689,-0.011125,0.043223,0.012521,-0.019685,0.021120,0.074565,0.032793,0.029294,-0.007399,-0.010995,-0.073599,0.191648,-0.112634
Gender,0.049854,0.002807,0.011866,1.000000,0.016745,0.017137,0.004140,0.035220,0.031492,0.040269,0.003863,-0.033564,-0.029511,0.024872,0.025190,-0.015871,0.039142,0.009841,-0.037225,-0.029264,-0.015597,-0.040314
AppSpendTime,0.011432,0.058522,0.054344,0.016745,1.000000,-0.005885,0.054701,0.029819,0.143023,0.003868,0.101230,0.008649,0.019555,0.067835,0.118535,-0.022072,0.142989,0.015658,0.034240,0.013031,0.013664,-0.019302
DeviceNumber,0.031821,-0.006871,-0.022958,0.017137,-0.005885,1.000000,-0.017670,-0.003250,0.022985,-0.001891,-0.032001,-0.002229,-0.019005,-0.000079,0.013259,-0.002322,-0.003913,0.022334,-0.032488,-0.022613,-0.016642,-0.004653
PreferedOrder,-0.209289,0.037361,0.028593,0.004140,0.054701,-0.017670,1.000000,-0.017671,0.011978,-0.016879,0.011555,0.073194,0.100668,-0.039576,-0.435424,0.056494,0.012895,-0.025626,0.007985,-0.055589,-0.147497,-0.066888
ScoreSatisfaction,-0.019884,0.012795,-0.045917,0.035220,0.029819,-0.003250,-0.017671,1.000000,0.053583,-0.031115,-0.023600,-0.009211,0.007846,0.027357,0.003473,-0.036049,-0.007636,0.058064,-0.023576,0.105481,0.006256,0.022742
AddressCount,0.247646,-0.012293,0.030689,0.031492,0.143023,0.022985,0.011978,0.053583,1.000000,-0.026399,0.015222,0.025212,0.045961,-0.062760,0.186688,-0.025863,0.125320,-0.003364,0.011834,0.043931,0.026307,0.009222
Complain,-0.018773,0.025137,-0.011125,0.040269,0.003868,-0.001891,-0.016879,-0.031115,-0.026399,1.000000,-0.005244,-0.003942,0.012173,-0.038469,0.000525,-0.001327,-0.001381,0.007044,-0.003720,0.250188,-0.000373,-0.013477
OrderAmountHikeFromlastYear,0.011396,0.030188,0.043223,0.003863,0.101230,-0.032001,0.011555,-0.023600,0.015222,-0.005244,1.000000,0.002012,-0.001312,0.003446,0.017045,0.010428,0.004029,-0.007674,0.003033,-0.012924,0.036488,-0.033727
Coupon,-0.080806,0.006202,0.012521,-0.033564,0.008649,-0.002229,0.073194,-0.009211,0.025212,-0.003942,0.002012,1.000000,0.517911,-0.248246,-0.141796,-0.015265,-0.058459,-0.013738,-0.030191,0.013677,0.016020,0.016958
OrderNumber,-0.140018,0.008502,-0.019685,-0.029511,0.019555,-0.019005,0.100668,0.007846,0.045961,0.012173,-0.001312,0.517911,1.000000,-0.396944,-0.226789,-0.031497,-0.075877,-0.022120,-0.038038,0.031765,0.021250,0.017622
DaySinceLastOrder,0.193261,0.011750,0.021120,0.024872,0.067835,-0.000079,-0.039576,0.027357,-0.062760,-0.038469,0.003446,-0.248246,-0.396944,1.000000,0.330720,-0.001469,0.164520,0.008795,0.050653,-0.152275,-0.009011,-0.021780
Cashback,0.497274,-0.009623,0.074565,0.025190,0.118535,0.013259,-0.435424,0.003473,0.186688,0.000525,0.017045,-0.141796,-0.226789,0.330720,1.000000,-0.047885,0.412752,0.044904,0.048915,-0.154118,-0.053895,0.001722
LoginDevice_Computer,-0.040953,0.025989,0.032793,-0.015871,-0.022072,-0.002322,0.056494,-0.036049,-0.025863,-0.001327,0.010428,-0.015265,-0.031497,-0.001469,-0.047885,1.000000,-0.628201,-0.028574,0.002643,0.051099,0.004938,-0.012032
LoginDevice_Mobile Phone,0.211048,-0.003065,0.029294,0.039142,0.142989,-0.003913,0.012895,-0.007636,0.125320,-0.001381,0.004029,-0.058459,-0.075877,0.164520,0.412752,-0.628201,1.000000,0.024368,0.027422,-0.111639,-0.099478,-0.027767
StatusOfMarital_Divorced,0.039177,-0.006431,-0.007399,0.009841,0.015658,0.022334,-0.025626,0.058064,-0.003364,0.007044,-0.007674,-0.013738,-0.022120,0.008795,0.044904,-0.028574,0.024368,1.000000,-0.447515,-0.024934,-0.012690,-0.006000
StatusOfMarital_Married,0.082534,0.027194,-0.010995,-0.037225,0.034240,-0.032488,0.007985,-0.023576,0.011834,-0.003720,0.003033,-0.030191,-0.038038,0.050653,0.048915,0.002643,0.027422,-0.447515,1.000000,-0.151024,0.017662,0.052027
Churn,-0.343945,0.076429,-0.073599,-0.029264,0.013031,-0.022613,-0.055589,0.105481,0.043931,0.250188,-0.012924,0.013677,0.031765,-0.152275,-0.154118,0.051099,-0.111639,-0.024934,-0.151024,1.000000,-0.084946,0.016970
TierOfCity_1,0.042795,-0.000502,0.191648,-0.015597,0.013664,-0.016642,-0.147497,0.006256,0.026307,-0.000373,0.036488,0.016020,0.021250,-0.009011,-0.053895,0.004938,-0.099478,-0.012690,0.017662,-0.084946,1.000000,-0.289547
TierOfCity_2,0.016223,-0.013904,-0.112634,-0.040314,-0.019302,-0.004653,-0.066888,0.022742,0.009222,-0.013477,-0.033727,0.016958,0.017622,-0.021780,0.001722,-0.012032,-0.027767,-0.006000,0.052027,0.016970,-0.289547,1.000000

In [20]:
stackted_data = df_corr.stack()
stackted_data['Churn']

Tenure                        -0.343945
HomeToWarehouse                0.076429
ModeOfPayment                 -0.073599
Gender                        -0.029264
AppSpendTime                   0.013031
DeviceNumber                  -0.022613
PreferedOrder                 -0.055589
ScoreSatisfaction              0.105481
AddressCount                   0.043931
Complain                       0.250188
OrderAmountHikeFromlastYear   -0.012924
Coupon                         0.013677
OrderNumber                    0.031765
DaySinceLastOrder             -0.152275
Cashback                      -0.154118
LoginDevice_Computer           0.051099
LoginDevice_Mobile Phone      -0.111639
StatusOfMarital_Divorced      -0.024934
StatusOfMarital_Married       -0.151024
Churn                          1.000000
TierOfCity_1                  -0.084946
TierOfCity_2                   0.016970
dtype: float64

In [21]:
df = df.drop('OrderAmountHikeFromlastYear',axis = 1)
df

,Tenure,HomeToWarehouse,ModeOfPayment,Gender,AppSpendTime,DeviceNumber,PreferedOrder,ScoreSatisfaction,AddressCount,Complain,Coupon,OrderNumber,DaySinceLastOrder,Cashback,LoginDevice_Computer,LoginDevice_Mobile Phone,StatusOfMarital_Divorced,StatusOfMarital_Married,Churn,TierOfCity_1,TierOfCity_2
0,4.0,6.0,0.411012,1,3.0,0.301776,0.364121,2,9,1,0.373890,0.311012,5.0,159.93,0,1,0,0,1,0,0
1,5.0,8.0,0.073535,0,3.0,0.422202,0.143694,3,7,1,0.182948,0.311012,0.0,120.90,0,0,0,0,1,1,0
2,0.0,30.0,0.411012,0,2.0,0.422202,0.143694,3,6,1,0.182948,0.311012,3.0,120.28,0,0,0,0,1,1,0
3,0.0,15.0,0.411012,0,2.0,0.422202,0.364121,5,8,0,0.182948,0.311012,3.0,134.07,0,0,0,0,1,0,0
4,0.0,12.0,0.048490,0,3.0,0.301776,0.143694,5,3,0,0.373890,0.311012,3.0,129.60,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5625,10.0,30.0,0.266607,0,3.0,0.049023,0.364121,1,6,0,0.373890,0.359680,4.0,150.71,1,0,0,1,0,1,0
5626,13.0,13.0,0.266607,0,3.0,0.156483,0.146714,5,6,0,0.373890,0.359680,4.0,224.91,0,1,0,1,0,1,0
5627,1.0,11.0,0.411012,0,3.0,0.049023,0.364121,4,3,1,0.373890,0.359680,4.0,186.42,0,1,0,1,0,1,0
5628,23.0,9.0,0.266607,0,4.0,0.156483,0.364121,4,4,0,0.227886,0.359680,9.0,178.90,1,0,0,1,0,0,0
5629,8.0,15.0,0.266607,0,3.0,0.049023,0.364121,3,4,0,0.227886,0.359680,3.0,169.04,0,1,0,1,0,1,0

In [22]:
outliers = {}
for i in df:
    q1 = df[i].quantile(0.25)
    q3 = df[i].quantile(0.75)
    iqr = q3-q1
    upperbound = q3 + 1.5*iqr
    lowerbound = q1 - 1.5*iqr
    outlier = df[(df[i] > upperbound) | (df[i] < lowerbound)]
    outliers[i] = len(outlier)
    if i == 'Cashback':
        df[i] = df[i].clip(lowerbound,upperbound)
        outliers[i+'_new'] = sum((df[i] > upperbound) | (df[i] < lowerbound))
outliers

{'Tenure': 4,
 'HomeToWarehouse': 2,
 'ModeOfPayment': 0,
 'Gender': 0,
 'AppSpendTime': 7,
 'DeviceNumber': 0,
 'PreferedOrder': 0,
 'ScoreSatisfaction': 0,
 'AddressCount': 4,
 'Complain': 0,
 'Coupon': 0,
 'OrderNumber': 0,
 'DaySinceLastOrder': 67,
 'Cashback': 438,
 'Cashback_new': 0,
 'LoginDevice_Computer': 0,
 'LoginDevice_Mobile Phone': 0,
 'StatusOfMarital_Divorced': 848,
 'StatusOfMarital_Married': 0,
 'Churn': 948,
 'TierOfCity_1': 0,
 'TierOfCity_2': 242}

In [23]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
clf = RandomForestClassifier(max_depth=6, random_state=0)
y = df['Churn']
x = df.drop('Churn',axis = 1)
zeros = sum(df['Churn'] == 0)
ones = sum(df['Churn'] == 1)
print(zeros,ones)

4682 948

In [25]:
zeros = df[df['Churn'] == 0].sample(frac= 0.2)
ones = df[df['Churn'] == 1]
df = pd.concat([ones,zeros])
df = df.sample(frac = 1.0).reset_index().drop(['index'],axis = 1)
df

,Tenure,HomeToWarehouse,ModeOfPayment,Gender,AppSpendTime,DeviceNumber,PreferedOrder,ScoreSatisfaction,AddressCount,Complain,Coupon,OrderNumber,DaySinceLastOrder,Cashback,LoginDevice_Computer,LoginDevice_Mobile Phone,StatusOfMarital_Divorced,StatusOfMarital_Married,Churn,TierOfCity_1,TierOfCity_2
0,1.0,34.0,0.109059,1,3.0,0.422202,0.146714,2,3,0,0.227886,0.359680,10.0,201.39,0,1,1,0,1,0,0
1,1.0,14.0,0.411012,0,4.0,0.422202,0.364121,3,3,0,0.227886,0.359680,2.0,173.83,0,1,1,0,1,1,0
2,0.0,14.0,0.048490,0,2.0,0.301776,0.143694,4,3,1,0.373890,0.311012,2.0,123.73,0,0,0,1,1,1,0
3,1.0,8.0,0.266607,0,2.0,0.301776,0.364121,4,5,0,0.182948,0.311012,4.0,148.55,0,0,0,1,1,1,0
4,1.0,16.0,0.411012,0,3.0,0.156483,0.364121,5,9,0,0.373890,0.359680,4.0,159.07,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1130,0.0,8.0,0.064831,1,2.0,0.301776,0.225755,1,2,1,0.182948,0.311012,3.0,137.60,1,0,0,0,0,1,0
1131,0.0,6.0,0.073535,0,2.0,0.301776,0.143694,2,2,1,0.022913,0.036590,8.0,126.86,0,0,0,0,1,1,0
1132,20.0,13.0,0.411012,0,2.0,0.422202,0.143694,1,10,1,0.373890,0.311012,0.0,123.80,1,0,0,1,1,1,0
1133,8.0,17.0,0.266607,0,3.0,0.422202,0.146714,5,3,1,0.373890,0.359680,3.0,198.84,1,0,0,1,0,1,0
1134,16.0,30.0,0.411012,0,3.0,0.301776,0.146714,5,7,1,0.227886,0.359680,2.0,204.48,0,1,0,0,1,0,0

In [26]:
y = df['Churn']
x = df.drop('Churn',axis = 1)
test_x = x[:int(len(x) * 0.2)]
train_x = x[int(len(x)*0.2) :]
test_y = y[:int(len(y) * 0.2)]
train_y = y[int(len(y)*0.2) :]

In [27]:
clf.fit(train_x, train_y)
prob = clf.predict_proba(test_x)
test_x['pred'] = clf.predict(test_x)
test_x['real'] = test_y
test_x['result'] = test_x['pred'] == test_x['real']
from sklearn.metrics import f1_score
print("f1_score", f1_score( test_x['real'], test_x['pred'] ))

f1_score 0.8955223880597014

C:\Users\User\AppData\Local\Temp\ipykernel_25028\2628376214.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_x['pred'] = clf.predict(test_x)
C:\Users\User\AppData\Local\Temp\ipykernel_25028\2628376214.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_x['real'] = test_y
C:\Users\User\AppData\Local\Temp\ipykernel_25028\2628376214.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_x['result'] = test_x['pred'] == test_x['real']